version: '3.1'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: devel
      POSTGRES_PASSWORD: devel
      POSTGRES_DB: rocket-diesel
    ports:
      - "5432:5432"
